### PR TITLE
Small corrections

### PR DESCRIPTION
**Pull request by Padlina**
To check:
- Open website in a new tab, check links in the popup
- Check navigation menu CSS, and try to click on the search icon
- look at the Steckbrief on the Convolute View, "Kommentar" item

### CODE REVIEW

**Comment by janCstoffregen** [comment]
When I klick on Steckbrief "Kommentar", I get the following:

<a class="jcepopup" data-mediabox-height="400" data-mediabox-width="600" href="index.php?option=com_k2&amp;view=item&amp;id=6348:manuskripte-1979-kommentar" target="_blank">Beschreibung</a>

Is this supposed to be like that?

**Comment by Padlina** [comment]
Well. By me I have the line:
 Kommentar: Beschreibung 
and on Kommentar you can't click, but you can click on Beschreibung and then it opens a popup with some data (not the correct one, though, for the momenet)

**Comment by janCstoffregen** [comment]
ok, sorry, I meant when I klick on Beschreibung, the follwoing appears:

````
<a class="jcepopup" data-mediabox-height="400" data-mediabox-width="800" href="index.php?option=com_k2&amp;view=item&amp;id=4379:notizbuch-1979-kommentar&amp;Itemid=232" target="_blank">Beschreibung</a>
````

So it does not convert the html.. is it supposed to be like that?

**Comment by janCstoffregen** [comment]
screen shot 2017-10-25 at 11 12 46

**Comment by Padlina** [comment]
Yes, I think so. There is this comment (from Sebastian): FIXME: Wert gibt im Moment lediglich den das Link-HTML-Element auf die Beschreibung zurück, anstatt den Inhalt zurückzugeben 
So, the data aren't yet there.

**Comment by janCstoffregen** [comment]
ok, I will merge it now

**Pull request merged**
