### PR TITLE
Nie 60 finalisiere synopsenansicht

### PR DESCRIPTION
**Pull request by Padlina**
Still missing for the Synopse VIew: Duplikate function and to check if it works with poems from Verestreutes. Also sorting could better done, but for the moment it isn't a priority (there is a TODO texgrid.component.ts about this.

### CODE REVIEW

**Comment by janCstoffregen** [comment]
Dear Roberta, what should we test?
Or just everything?

**Comment by Padlina** [comment]
Sorry ;) To test: all functions without the still missing ones (Duplikate and poems from Verstreutes). Thank you.

**Comment by janCstoffregen** [comment]
ok, sieht gut aus, ich resolve noch den conflict wegen meines letzten pr

**Comment by janCstoffregen** [comment]
can the branch be deleted?

**Pull request merged**
